spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://db.codingmate24.kro.kr:3306/develop
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:log4jdbc:mysql://db.coding-study.com:3306/dev.cdstudy
    username: devuser
    password: devuser


mybatis:
  type-aliases-package: com.prj.codingstudy.core.domain.**
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR

jwt:
  expiration_time:
    access-token: 3600
    refresh-token: 12800
  # 86400000 1일
  secret: a5aa5849aa6f272c8d8621c32c791ec71a166e85d47a59a85e7652bd32c414eb

server:
  # address: db.coding-study.com
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true




